### ISSUE TITLE
Feat: Force Push UI

### ISSUE THREAD

**Issue by mahaloz** [angr/binsync#135]
## Problem
There are two scenarios where this is applicable:
1. BinSync messes up and did not track a change you made to a function or struct
2. You did not have BinSync open when you made changes to something

Now you need to force push some data to the BinSync repo since it was not tracked. The first problem is that the current UI of BinSync only shows functions and globals (including structs) that were changed by someone... so how could you click force-push on it if it's not shown in the table. 

## Proposal
To fix these issues, we need to make a Functions and Globals table that looks just like the BinSync Control Panel tables in a popup.
These two tables should show **all** the functions and globals in the whole program. You should be able to select each many functions/globals. Then after selecting them you should be able to click a `Force Push` button. Something like this:

![force_push](https://user-images.githubusercontent.com/21327264/172222829-a8e0f64a-8e80-4331-a33c-e34af6f60d72.jpg)

The backend does not need to be completed in this task. Instead, proving that selecting the functions/globals returns a list of all the selected objects.

**Comment by Lukas-Dresel** [comment]
I would like to also request a "Push current function" button for convenience :)

**Comment by mahaloz** [comment]
Closed with #161
