### ISSUE TITLE
Binja Plugin License is BSD but Repo License is MIT

### ISSUE THREAD

**Issue by zachsez** [angr/binsync#70]
See line 9: https://github.com/angr/binsync/blob/master/plugins/binja_binsync/plugin.json

**Comment by ltfish** [comment]
@mahaloz we BSD-2 everything. Why MIT?

**Comment by mahaloz** [comment]
@ltfish I did MIT because I liked the generality of it; we can switch to BSD if you recommend it since I have little experience in license choices

**Comment by mahaloz** [comment]
Updated to BSD2
